services:
  xdrd:
    image: sjg/xdrd:latest
    container_name: xdrd
    ports:
      - "7999:7373"
    environment:
      - XDRD_PASSWORD=DX2137
    restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
